apache/doris-thirdparty

src/client/InputStreamImpl.cpp

When seeking to target offset in one hdfs block, it will read all data between current offset and target offset.
This is very time consuming when the block size is very large.
For ssb orc 30G test suite on doris, it will improve 2.3x

improve seek performence when seeking a wide range

---

.github/workflows/build.yml

Add a workflow to build libraries automatically.
1. The workflow will trigger the build process if it detects some changes was made for third-party libraries in [apache/doris](https://github.com/apache/doris) and it will be scheduled every 30 minutes.
2. Release the prebuilts automatically.

[chore](workflow) Add a workflow to build libraries automatically

---

CHANGELOG.md
src/CMakeLists.txt
src/client/Permission.cpp

When doris be getFileStatus from HDFS2 server, libhdfs3 will throw exception because of the permissio code returned by hdfs2 server is greater than  1<<12.  
The bit 12 of  permissio code is aclBit which has been deprecated in hadoop3. so we remove the check code in libhdfs3, same as hadoop3 java project.

[Enhancement] make libhdfs3 compatible with hdfs2 server

---

.github/workflows/build-1.2.yml
.github/workflows/build.yml

Currently, if the workflows failed, we should re-trigger the workflows manually. This PR introduces a way to do this work automatically.

[chore](workflow) Re-build the third-party libraries automatically when the workflows fail

---

.github/workflows/build.yml

Although the release `Apache Doris Third Party Prebuilt` was created months ago, its content is changing all the time.
Because the artifacts are needed by BE UT workflows, we overwrite them in workflow instead of creating a brand new release. As a consequence, the release `Apache Doris Third Party Prebuilt` is considered as a obsolete one.
I think we can always mark it as a latest release because the artifacts are built against the _**master**_ branch of `Apache Doris`. After that, we can access the artifacts more conveniently.

[chore](workflow) Mark Apache Doris Third Party Prebuilt as a latest release

---

src/client/CryptoCodec.cpp

For AES, the algorithm block is fixed size of 128 bits.
http://en.wikipedia.org/wiki/Advanced_Encryption_Standard

[Fix](libhdfs3) Fix AES Block size to 128 bits.

---

src/client/CryptoCodec.cpp

e.g. Client called `seek(3)`, then called `seek(0)`。`seek(0)` did not reset stream offset of CryptoCodec, it still use CryptoCodec calculate information when calling `seek(3)`。It caused de/crypto error.
Fix seek(0) does not reset stream offset of CryptoCodec.

[Fix](libhdfs3) Fix seek(0) does not reset stream offset of CryptoCodec.

---

.github/workflows/build-1.2.yml
.github/workflows/build.yml

In [doris#17292](https://github.com/apache/doris/pull/17292), we use LLVM Clang to build [Apache Doris](https://github.com/apache/doris) by default on macOS. Therefore, we should also use LLVM Clang to build the third-party libraries.

[chore](github) Use LLVM Clang to build the libraries by default on macOS

---

.github/workflows/build.yml
src/core/CLucene/index/_Term.h
src/core/CLucene/search/BooleanQuery.cpp
src/core/CLucene/search/MultiPhraseQuery.cpp
src/core/CLucene/util/Equators.h
src/core/CLucene/util/_Arrays.h
src/test/index/TestTermVectorsReader.cpp

Changes:
1. `std::binary_function` was marked deprecated in C++ 11 and we should remove it.
2. Add a workflow to validate the build on multiple platforms.

[chore] Remove deprecated templates

---

.github/workflows/build-1.2.yml
.github/workflows/build.yml

Clang 16 was released last week and we haven't ported the codebase to it. If Homebrew bumped the version of LLVM, our workflows would fail.

[chore](macOS) Specify the version of LLVM for Homebrew to install it

---

.github/workflows/build.yml

We should mark the build workflow required. Therefore, we should assign names to the build jobs in order to set up the `.asf.yml`.

[chore] Assign names to the build jobs

---

src/contribs-lib/CLucene/analysis/LanguageBasedAnalyzer.cpp
src/contribs-lib/CLucene/analysis/LanguageBasedAnalyzer.h
src/contribs-lib/CLucene/analysis/jieba/ChineseTokenizer.cpp
src/contribs-lib/CLucene/analysis/jieba/ChineseTokenizer.h
src/core/CLucene/search/IndexSearcher.cpp
src/core/CLucene/search/TermQuery.cpp
src/core/CLucene/util/bkd/bkd_writer.cpp

1. Failure to implement the reusableTokenStream method results in token stream being created each time, which can cause memory leaks.
2. Refactored the Jieba instance using singleton.
3. Replaced new norm with nullptr in TermScorer to save memory.

[Fix](chinese analyzer) fix memory leak in chinese analyzer

---

.github/workflows/build.yml
src/ext/for/bitutil.c
src/ext/for/bitutil.h

Currently, some errors occur when building clucene by GCC-12.2. This PR fixes these errors.

[chore] Porting to GCC 12.2

---

src/core/CLucene/index/IndexWriter.cpp
src/core/CLucene/index/SegmentMergeInfo.cpp
src/core/CLucene/index/_SegmentMergeInfo.h

Description: This pull request addresses the issue of index compaction performance by introducing a priority queue to better manage the process. This update involves changes in IndexWriter.cpp, SegmentMergeInfo.cpp, and _SegmentMergeInfo.h. The key modifications include:
1. Replacing the previous approach for finding the smallest term and constructing a dest_idx_bitmap with a more efficient priority queue based approach.
2. Introducing a new postingQueue class to manage the document merging process.
3. Implementing a new DestDoc struct to store relevant information for each document in the merging process.
4. Refactoring the mergeTerms() method to use the new priority queue based approach.
These changes have resulted in improved performance during the index compaction process, leading to …

[Improvement](index compaction) improve index compaction perf by introducing priority queue

---

.clang-format
c++/include/orc/Reader.hh
c++/include/orc/Type.hh
c++/src/ColumnReader.cc
c++/src/ColumnReader.hh
c++/src/Options.hh
c++/src/Reader.cc
c++/src/Reader.hh
c++/src/TypeImpl.cc
c++/src/TypeImpl.hh

Refer to orc java implementation: [LazyIO of non-filter columns in the presence of filters](https://issues.apache.org/jira/browse/ORC-742)
Note: Row-level filtering by selection vector is currently not implemented, will do it in future PR.

[Feature] Implements ORC lazy materialization.

---

c++/include/orc/Reader.hh
c++/include/orc/Type.hh
c++/src/ColumnReader.cc
c++/src/ColumnReader.hh
c++/src/Reader.cc
c++/src/Reader.hh
c++/src/TypeImpl.cc

1. Implements selection vector for ORC lazy materialization. From the test, currently implements float/double, date/timestamp, decimal, string dict types for better performance, and other types have performance penalty.
2. Decrease `loadStripIndex()` call count.
3. Adjust code format.

[Feature] Implements selection vector for ORC lazy materialization.

---

.github/workflows/build.yml

[apache/doris #19325](https://github.com/apache/doris/pull/19325) upgraded the toolchains, we should keep consistent with the repository [apache/doris](https://github.com/apache/doris).

[chore](workflow) Upgrade the toolchains to build libraries

---

.github/workflows/build-1.2.yml
.github/workflows/build.yml

After introducing hadoop in thirdparty, we need to use jdk8 to compile it.
If using jdk11 and run BE using jdk8, it will return error: 
`NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;`

[build] change jdk11 to jdk8

---

.github/workflows/build-1.2.yml
.github/workflows/build.yml

#80 didn't set the environment variables and the workflow still uses OpenJDK 11 to build the packages.

[chore](workflow) Set up environment variables for OpenJDK 8

---

src/core/CLucene/analysis/standard/StandardTokenizer.cpp

make standard analyzer like this:
origin text 
```
陕西省西安市高新区创业大厦A座，我的手机号码是14243907889,邮箱是[474696115@qq.com](mailto:474696115@qq.com)，,ip是113.444.556.777.222小数2.2333多大事，this information is created automatically.
```
after tokenized
```
陕|西|省|西|安|市|高|新|区|创|业|大|厦|座|我|的|手|机|号|码|是|14243907889|邮|箱|是|474696115|qq.com|ip|是|113.444.556.777.222|小|数|2.2333|多|大|事|information|created|automatically|
```

[Fix](standard analyzer) change standard analyzer CJK tokenizer, align it to newest standard analzyer mode

---

.github/workflows/build.yml

There is not enough disk space to build the third-party libraries, we should increase the build space.

[chore](workflow) Increase the build space for master branch

---

src/shared/CLucene/config/utf8.cpp

1. string to wstring buffer overflow

[fix] fix string to wstring buffer overflow

---

src/core/CLucene/util/PFORUtil.cpp
src/core/CLucene/util/PFORUtil.h

fix building error in arm:
```
/root/teamcity/teamcity-agent-0/work/afe9024ed542c677/be/src/clucene/src/core/CLucene/util/PFORUtil.h:21:10: fatal error: cpuid.h: No such file or directory
[02:25:00 ](http://43.132.222.7:8111/buildConfiguration/Doris_ArmPipeline_P0Regression/217163?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandPull+Request+Details=true&expandBuildProblemsSection=true&showLog=217163_1714_1714&logFilter=debug&logView=flowAware)     21 | #include <cpuid.h>
[02:25:00 ](http://43.132.222.7:8111/buildConfiguration/Doris_ArmPipeline_P0Regression/217163?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandPull+Request+Details=true&expandBuildProblemsSection=true&showLog=217163_1715_1715&logFilter=debug&logView=flowAware)        | …
```

[Fix](PFOR) fix build error in arm

---

src/core/CLucene/index/IndexWriter.cpp

Doris compaction translation vec:
```cpp
trans_vec
<<dest_idx_num, dest_docId>>
the first level vector: index indicates src segment.
the second level vector: index indicates row id of source segment,
value indicates row id of destination segment.
<UINT32_MAX, UINT32_MAX> indicates current row not exist.
```
When `dest_idx_num` and `desc_docId` is `UINT32_MAX`, it indicates that the current row not exists. 
So we cannot add this doc to the inverted index either.

[fix](index compaction)ignore doc which dose not exist in destination segment

---

c++/test/TestBloomFilter.cc

Rename `TestBloomFilter` to `TestOrcBloomFilter` to avoid conflict.

[UnitTest] Rename `TestBloomFilter` to `TestOrcBloomFilter` to avoid conflict.

---

CMakeLists.txt
src/core/CLucene/util/stringUtil.h

Turn on `BUILD_CONTRIBS_LIB` by default.

[fix](compile)Fix compile error in MacOS

---

src/core/CLucene/store/_RAMDirectory.h

Change `sizeInBytes` from private to public to access out of CLucene.

[opt](RAM dir)fix compile error in _RAMDirectory

---

.github/workflows/build.yml

boost jfrog download url is down.
Same issue: https://github.com/boostorg/boost/issues/842
So I change the download url to boost io temporarylly.

[fix](build)update available boost download url

---

src/core/CLucene/index/IndexWriter.cpp
src/core/CLucene/index/IndexWriter.h
src/test/CMakeLists.txt
src/test/index/TestIndexCompaction.cpp
src/test/test.h
src/test/tests.cpp

Spport merge null_bitmap during index compaction.
We read the source indices null_bitmap files and write them to new ones according to the translation vector doc id mapping.

[fix](index compaction) Support merge null_bitmap during index compaction

---

src/contribs-lib/CLucene/snowball/libstemmer/libstemmer.c

vallish@Vallishs-MacBook-Air doris-thirdparty % cat check.txt | grep memleak
src/contribs-lib/CLucene/snowball/libstemmer/libstemmer.c:42:29: error: Memory leak: stemmer [memleak]
in failure path added free for the pointer.

(fix)[mlk] if sb_getenc is unknown, then sb_stemmer_new API will leak mem

---

src/core/CLucene/index/SDocumentWriter.cpp

revert https://github.com/apache/doris-thirdparty/pull/156
core stack trace
```
I0000 00:00:00.000000 3433156 vlog_is_on.cc:197] RAW: Set VLOG level for "*" to 10
*** Query id: 0-0 ***
*** tablet id: 0 ***
*** Aborted at 1708977071 (unix time) try "date -d @1708977071" if you are using GNU date ***
*** Current BE git commitID: 003a815b63 ***
*** SIGSEGV unknown detail explain (@0x0) received by PID 3433156 (TID 2446483 OR 0x7f0e53c8b640) from PID 0; stack trace: ***
0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /home/zcp/repo_center/doris_release/doris/be/src/common/signal_handler.h:417
1# os::Linux::chained_handler(int, siginfo*, void*) in /app/java/jdk/jre/lib/amd64/server/libjvm.so
2# JVM_handle_linux_signal in …
```

[fix](write)revert comparePostings due to write core

---

src/core/CLucene/index/IndexWriter.cpp

When we encounter an int32_max value during index compaction, it should not be added to the destPostingQueue.
This will cause the posting of subsequent docs to be ignored, which will cause the index file compaction to fail.

[fix](index compaction)Remove INT32_MAX out of destPostingQueues

---

src/core/CLucene/index/IndexWriter.cpp

This pull request addresses an issue within the closeInternal method. 
When Thread A invokes closeInternal and encounters a CLucene error, the method exits without setting the closing flag back to false. 
As a result, if another Thread B subsequently calls closeInternal and enters the waitForClose method, it becomes trapped in an infinite loop.

[Fix](index writer) fix dead lock when closeInternal catches CLuceneError

---

src/core/CLucene/index/IndexWriter.cpp

From #207 
This pull request addresses an issue within the closeInternal method.  When Thread A invokes closeInternal and encounters a CLucene error, the method exits without setting the closing flag back to false.  As a result, if another Thread B subsequently calls closeInternal and enters the waitForClose method, it becomes trapped in an infinite loop.

[Pick 2.0](index writer) fix dead lock when closeInternal catches CLuceneError (#207)

---

src/core/CLucene/index/IndexWriter.cpp

clucene will coredump if doris try to re-close index writer when encountering error in dir->close(), because in this situation, doc writer is already deleted and set to nullptr

[Fix](index writer) fix core if docWriter nullptr when IndexWriter doFlush

---

.github/workflows/build-1.2.yml
.github/workflows/build-2.0.yml
.github/workflows/build.yml

Recently, GitHub actions provide macOS arm64 environment to run workflows. Therefore, we can use this environment to build our macOS arm64 packages.

[chore](workflow) Use GitHub Actions to build arm64 packages

---

src/core/CLucene/document/Document.cpp
src/core/CLucene/document/Document.h
src/core/CLucene/index/SDocumentWriter.cpp
src/core/CLucene/index/SDocumentWriter.h

https://github.com/apache/doris-thirdparty/pull/200
https://github.com/apache/doris-thirdparty/pull/208

[Feature]Support array reuse field

---

hadoop-common-project/hadoop-common/src/CMakeLists.txt

before, in arm which before arm-v8 or x86 which before sse4.2, we will get wrong result of crc32 support. it will lead to compiliation error.

fix: do really detection of crc32 instructions

---

src/core/CLucene/util/CLStreams.h
src/test/CMakeLists.txt
src/test/test.h
src/test/tests.cpp
src/test/util/TestStringReader.cpp

It should only copy the length passed from argument, instead of `length + 1`, which may cause ASAN global-buffer-overflow.
```
void init(const void *_value, int32_t _length, bool copyData = true) override {
const size_t length = _length;
this->pos = 0;
if (copyData) {
T *tmp = (T *) this->value;
if (tmp == NULL || !this->ownValue) {
tmp = _CL_NEWARRAY(T, length + 1);
this->buffer_size = length;
} else if (length > this->buffer_size || length < (this->buffer_size / 2)) {//expand, or shrink
tmp = (T *) realloc(tmp, sizeof(T) * (length + 1));
this->buffer_size = length;
}
memcpy(tmp, _value, length + 1);  ///////////////// THIS IS THE BUGGY LINE  //////////
this->value = tmp;
} else {
if (ownValue && this->value != NULL) {
_CLDELETE_LARRAY((T *) this->value);
}
this->value = (T *)_value; …
```

fix CLStream memcpy read 1 extra byte

---

src/core/CLucene/index/FieldInfos.cpp
src/core/CLucene/index/IndexVersion.h
src/core/CLucene/index/IndexWriter.cpp
src/core/CLucene/index/IndexWriter.h
src/core/CLucene/index/SDocumentWriter.cpp
src/core/CLucene/index/SDocumentWriter.h
src/core/CLucene/index/SegmentTermDocs.cpp
src/core/CLucene/index/SegmentTermPositions.cpp
src/core/CLucene/index/_FieldInfos.h
src/core/CLucene/index/_SegmentHeader.h
src/core/CLucene/util/PFORUtil.cpp
src/core/CLucene/util/PFORUtil.h
src/test/CMakeLists.txt
src/test/index/TestIndexCompress.cpp
src/test/test.h
src/test/tests.cpp

1. Optimize position information in the inverted index

[opt](inverted index) Optimize the compression of inverted index position information

---

src/core/CLucene/index/IndexWriter.cpp

If the doc frequency of a term is 0, it means the term is deleted. So we should not write it.

[fix](index compaction)Skip writing terms with a doc frequency of 0

---

c++/src/ColumnReader.cc

[Fix] Fix late late materialization of list type by reading all of children.

[Fix] Fix late late materialization of list type by reading all of children.

---

c++/src/Statistics.cc
c++/src/sargs/PredicateLeaf.cc

ORC added hasNull statistical information in version 0.12, but the c++ version of ORC reader is not correctly compatible with versions before 0.12. Referring to the implementation of java, we modified the judgment method of has_null.
```java
ColumnStatisticsImpl(OrcProto.ColumnStatistics stats) {
...
if (stats.hasHasNull()) {
hasNull = stats.getHasNull();
} else {
hasNull = true;
}
}
```

[fix](orc) Fix has null statistics for forward compatibility

---

src/core/CLucene/util/bkd/bkd_reader.h

Make ram_bytes_used public because doris need to use it to calculate memory used

[fix](bkd) make ram_bytes_used for bkd reader public

---

.github/workflows/build.yml
.github/workflows/clucene-ut.yml
CMakeLists.txt
src/core/CLucene/index/IndexWriter.cpp
src/core/CLucene/index/IndexWriter.h
src/core/CLucene/index/SDocumentWriter.cpp
src/core/CLucene/index/TermInfosWriter.cpp
src/core/CLucene/index/_TermInfosWriter.h
src/core/CLucene/store/IndexInput.cpp
src/core/CLucene/store/IndexOutput.cpp
src/core/CLucene/store/IndexOutput.h
src/ext/sse2neon/sse2neon.h
src/test/CMakeLists.txt
src/test/store/TestUTF8Chars.cpp
src/test/test.h
src/test/tests.cpp

[fix](unicode) fix 4 bytes unicode read and write bug 

---

hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java
hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs/hdfs.c
hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs/include/hdfs/hdfs.h

Revert #173 but keep `hdfsBuilderSetPrincipal()` in hdfs.h.
We can not only use `hdfsBuilderSetUsername()` to set principal. If user is set, the `UserGroupInformation.getBestUGI()`
will try getting ugi from remote user, not from kerberos subject.

Revert "[fix](tgt)hadoop kerberos support renew TGT by keytab (#173)" but remain principal interface

---

.github/workflows/build.yml

Because the default cmake version is upgraded to 4.0, which don't support minimum version of cmake less than 3.1.
But some deps like libevent need 3.1

[build] use fixed cmake version

---

c++/src/Reader.cc

[Fix] Clear streams map when all row groups are filtered by row group stats, despite stripe stats remaining unfiltered.

[Fix] Clear streams map when all row groups are filtered by row group stats, despite stripe stats remaining unfiltered.

---

c++/src/ColumnReader.cc
c++/src/ColumnReader.hh
c++/src/Reader.cc

When using an older version of pyorc (e.g., pyorc-0.3.0), If there are null values in the data, a present stream will be generated for the top level struct column.
However, this behavior does not occur in newer versions of pyorc (e.g., pyorc-0.10.0) or in ORC files generated by tools like Hive or Spark.
Therefore, the present stream generated by the older version causes the ORC file to be read twice during late materialization, resulting in an error 'bad read in next buffer' during the second read. The current solution is to avoid reading the present stream if it is in the top level struct column.

[Fix] Fixed issue with top level struct column having present stream failing to access repeatedly when late materialization occurs.

---

c++/src/Reader.cc

[Fix] Revert `computeRGIdx()` changes in #309, it will fix in the next PR.

[Fix] Revert PR309 computeRGIdx() changes, it will fix in the next PR.

---

c++/include/orc/Type.hh
c++/src/ColumnReader.cc
c++/src/Reader.cc
c++/src/TypeImpl.cc

Fix complex type late materialization.
Currently Filter/Non Filter Node types:
```
/**
* Filter Node Types:
*
* FILTER_CHILD: Primitive type that is a filter column.
* FILTER_PARENT: Compound type that may contain both filter and non-filter children.
* FILTER_COMPOUND_ELEMENT: Compound type that is a filter element (list/map).
*                         The entire column will be read, and must have only filter children.
* NON_FILTER: Non-filter column.
*
* Example:
* struct<name:string,
*        age:int,
*        address:struct<city:string,
*                       zip:int,
*                       location:struct<latitude:double, longitude:double>>,
*        hobbies:list<struct<name:string, level:int>>,
*        scores:map<string, struct<subject:string, grade:int>>>
*
* Filter columns: …
```

[fix] Fix complex type late materialization.

---

c++/src/Reader.cc
c++/src/StripeStream.cc
c++/src/StripeStream.hh

[Optimize] Optimize stripe footer multiple reads.

---

c++/src/Reader.cc

[fix] Load StripeIndex if searchArgument not exist when filter is not null.

---

c++/src/ByteRLE.cc
c++/test/TestWriter.cc

[fix](cherry-pick) ORC-1525: Fix bad read in RleDecoderV2::readByte.

---

c++/src/Compression.cc

[fix] Updated ZlibDecompressionStreamByLibDeflate::getName() to be the same as ZlibDecompressionStream::getName() to keep unit tests correct.
