src/client/LocalBlockReader.cpp
src/client/RemoteBlockReader.cpp
src/common/Crc32.h

support crc32 checksum for hdfs

support crc32 checksum

---

.asf.yaml
README.md

protect following branches:
1. main
2. bdbje
3. libhdfs3

[github] add branch protection

---

.github/workflows/build.yml

Display status in the release page.

[chore](github) Optimize the workflow Build

---

.github/workflows/build-1.2.yml

Apache Doris made the branch `branch-1.2-lts` protected. As a result, all pull requests for this branch should be checked before merging it. Therefore, we should add a build workflow for this branch.

Add a build workflow for 1.2-lts

---

src/client/InputStreamImpl.cpp
src/client/OutputStreamImpl.cpp

If kms url is empty, do not call `getfileStatus()` rpc.

[Enhancement] If kms url is empty, do not call getfileStatus() rpc.

---

src/rpc/RpcChannel.cpp

sometimes the auths may contain unsupported auth method,
such as OAUTHBEARER. should skip it and try next method.

[fix] skip unsupported auth method

---

src/shared/CLucene/LuceneThreads.h
src/shared/CLucene/config/_threads.h

fix compatible problem find in macos build.

[Fix](thread) fix thread compatibility in diffrent compilation enviroment

---

.github/workflows/build-1.2.yml
.github/workflows/build.yml

See [https://github.com/apache/doris-thirdparty/actions/runs/4278137200/jobs/7447605219](https://github.com/apache/doris-thirdparty/actions/runs/4278137200/jobs/7447605219).

[chore](workflow) Don't upgrade the packages to fix the potential failures

---

.github/workflows/build.yml
cmake/TurboPFOR.cmake

Currently, some errors occur when building clucene by Clang-16. This PR fixes these errors.

[chore] Porting to Clang-16

---

src/core/CLucene/util/CLStreams.h
src/core/CLucene/util/bkd/bkd_reader.h
src/core/CLucene/util/bkd/heap_point_writer.h
src/core/CLucene/util/bkd/index_tree.h
src/core/CLucene/util/bkd/point_reader.h
src/core/CLucene/util/bkd/point_writer.h

I want add -Wno-non-virtual-dtor to doris, so we need fix clucene's warning

[Chore](build) fix non-virtual dtor for base class

---

.github/workflows/build-1.2.yml
.github/workflows/build.yml

[build] build thirdparty by gcc

---

src/contribs-lib/CLucene/analysis/LanguageBasedAnalyzer.cpp
src/contribs-lib/CLucene/analysis/jieba/FullSegment.hpp
src/contribs-lib/CLucene/analysis/jieba/Jieba.hpp
src/contribs-lib/CLucene/analysis/jieba/MixSegment.hpp
src/contribs-lib/CLucene/analysis/jieba/Unicode.hpp

1. jieba default example
(1)
{"qid": "qid_1396667505999406632", "category": "游戏-完美游戏-赤壁", "title": "为什么装备无法分解22级的时候，到巧匠赵灵处领取“工匠之术”任务 ", "desc": "22级的时候，到巧匠赵灵处领取“工匠之术”任务，任务要求到铁匠樊建处购买22级使用的二阶到赵灵处分解。我买了武器，到赵灵处，点击：“装备分解”！可是，武器放不了那框里，无法分解！请问怎么回事啊？谢谢！", "answer": "直接拖放是放不上去的，按鼠标的左键（在装备上）双击就会放上去，你试一下 \r\n"}
qid|qid|1396667505999406632|category|游戏|完美|游戏|赤壁|title|装备|无法|分解|22|级|巧匠|赵灵处|领取|工匠|之术|任务|desc|22|级|巧匠|赵灵处|领取|工匠|之术|任务|任务|要求|铁匠|樊建|处|购买|22|级|使用|二阶|赵灵处|分解|买|武器|赵灵处|点击|装备|分解|武器|放|不了|框里|无法|分解|请问|怎么回事|谢谢|answer|直接|拖放|放|上去|鼠标|左键|装备|双击|会|放上去|试一下|r|n|
(2)
赵 丽 颖 赵, 丽, 颖
赵|丽|颖|赵|丽|颖|

[Feature](jieba) jieba add stop filter

---

.github/workflows/build-2.0.yml

There is not enough disk space to build the third-party libraries, we should increase the build space.

[chore](workflow) Increase the build space

---

src/core/CLucene/index/TermInfosWriter.cpp
src/core/CLucene/store/IndexOutput.cpp
src/core/CLucene/store/IndexOutput.h
src/core/CLucene/util/stringUtil.h
src/shared/CLucene/config/utf8.cpp
src/test/CMakeLists.txt
src/test/test.h
src/test/tests.cpp
src/test/util/testStrConvert.cpp

1. supports utf8 and non-utf8 strings
2. optimize string_to_wstring function

[fix] compatible with utf8 and invalid utf8

---

c++/src/ColumnReader.cc

Optimize the performance of reading decimals.
```
MySQL [hive.tpch100_orc]> select count(l_extendedprice) from lineitem;
+------------------------+
| count(l_extendedprice) |
+------------------------+
|              600037902 |
+------------------------+
1 row in set (1.88 sec)
MySQL [hive.tpch100_orc]> select count(l_extendedprice) from lineitem;
+------------------------+
| count(l_extendedprice) |
+------------------------+
|              600037902 |
+------------------------+
1 row in set (1.36 sec)
```

[Optimize] Optimize the performance of reading decimals.

---

src/core/CLucene/debug/error.h
src/core/CLucene/index/IndexWriter.cpp
src/core/CLucene/index/SDocumentWriter.cpp

[fix](keyword) fix the keyword type index length limit

---

src/contribs-lib/CLucene/analysis/LanguageBasedAnalyzer.cpp
src/contribs-lib/CLucene/analysis/LanguageBasedAnalyzer.h
src/contribs-lib/CLucene/analysis/jieba/ChineseTokenizer.cpp
src/core/CLucene/analysis/AnalysisHeader.h
src/core/CLucene/analysis/Analyzers.h
src/core/CLucene/analysis/standard95/StandardAnalyzer.h
src/core/CLucene/index/IndexWriter.cpp

1. chinese tokenzier use sDocument

[Optimize](chinese) Optimize chinese tokenizer index process

---

c++/include/orc/Reader.hh
c++/src/Reader.cc
c++/src/Reader.hh

add `getNumberOfRows()`, so that we can get the number of rows in given range

[feature](orc) add getNumberOfRows in RowReader

---

c++/src/ColumnReader.cc

Fix orc decimal128 scale issue.

[Fix] Fix orc decimal128 scale issue.

---

src/core/CLucene/index/TermInfosWriter.cpp
src/core/CLucene/index/_TermInfosWriter.h

Reverts apache/doris-thirdparty#149

Revert "[fix](compile) fix clucene-2.0 compile error"

---

src/core/CLucene/index/SDocumentWriter.cpp
src/core/CLucene/util/SSEUtil.h
src/core/CLucene/util/stringUtil.h

[opt](write)use more efficient string_compare from doris (#155)

---

CMakeLists.txt
src/core/CLucene/util/stringUtil.h

(pick)[fix](compile)Fix compile error in MacOS (#162)

---

src/core/CLucene/index/SDocumentWriter.cpp
src/core/CLucene/index/SDocumentWriter.h
src/core/CLucene/store/_RAMDirectory.h

[pick] fix compile error in _RAMDirectory and maxBufferedDocs not working 

---

.github/workflows/build.yml

[fix](build)update available boost download url (#171)

---

src/core/CLucene/analysis/AnalysisHeader.h
src/core/CLucene/util/CLStreams.h
src/core/CLucene/util/PriorityQueue.h
src/core/CLucene/util/bkd/bkd_docid_iterator.h
src/core/CLucene/util/stringUtil.h

[Clucene](chore) fix some implicit conversion

---

src/core/CLucene/document/Document.cpp
src/core/CLucene/document/Document.h
src/core/CLucene/index/SDocumentWriter.cpp
src/core/CLucene/index/SDocumentWriter.h

add  needResetFieldData for doc to make doc can get more field data when call 
``` add_document() ```

support multi add different field for one doc

---

src/core/CLucene/index/IndexWriter.cpp
src/core/CLucene/index/IndexWriter.h

Reverts apache/doris-thirdparty#203

Revert "[opt](chinese) chinese tokenizer lowercase interface"

---

src/core/CLucene/index/IndexWriter.cpp

[Pick 2.0](index writer) fix docWriter is null, when reenter close

---

c++/src/TypeImpl.cc
c++/test/TestType.cc

same as https://github.com/apache/orc/pull/1954

better column name error description

---

src/core/CLucene/index/IndexWriter.cpp

[Pick 2.0](index compaction) fix memory leak for index compaction

---

src/contribs-lib/CLucene/analysis/LanguageBasedAnalyzer.cpp
src/contribs-lib/CLucene/analysis/jieba/ChineseTokenizer.cpp
src/contribs-lib/CLucene/analysis/jieba/ChineseTokenizer.h
src/core/CLucene/analysis/AnalysisHeader.h
src/core/CLucene/analysis/Analyzers.cpp
src/core/CLucene/analysis/Analyzers.h
src/core/CLucene/analysis/standard95/StandardAnalyzer.h
src/core/CLucene/analysis/standard95/StandardTokenizer.h
src/core/CLucene/document/Field.cpp
src/core/CLucene/document/Field.h

[Pick 2.0](analyzer) add reader ownership for chinese and standard analyzer

---

src/core/CLucene/debug/error.h

add error code:  CL_ERR_FileNotFound

[opt](error code) add error code: FileNotFound

---

src/core/CLucene/debug/error.h

pick from [#227](https://github.com/apache/doris-thirdparty/pull/227)

[pick 2.0] add error code FileNotFound

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryColumnHandle.java

The detail problem: https://github.com/trinodb/trino/pull/21523

Fix the serialization issue of the isPushdownSupported variable in the BigQueryColumnHandle class.

---

src/core/CLucene/search/SloppyPhraseScorer.cpp

[Pick 2.0](inverted index) fix the heap-buffer-overflow issue in clucene sop_phrase_query

---

hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs/exception.c
hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs/hdfs.c
hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs/include/hdfs/hdfs.h

[Feature] (hdfs-native-client) Added custom logger to print errors to stderr instead.

[Feature](hdfs-native-client) Added custom logger to print errors to stderr instead.

---

hadoop-common-project/hadoop-common/src/CMakeLists.txt

which was introduced by https://github.com/apache/doris-thirdparty/pull/233

fix: compile hadoop on arm with crc

---

src/core/CLucene/index/IndexWriter.cpp

[fix](index compaction)Skip writing terms with a doc frequency of 0 (#248)

---

c++/test/TestStripeIndexStatistics.cc

fix orc be ut TestStripeIndexStatistics
relate pr: https://github.com/apache/doris-thirdparty/pull/259

[fix](orc) fix be ut

---

cmake/FindICU.cmake
src/core/CLucene/analysis/icu/DefaultICUTokenizerConfig.cpp
src/core/CLucene/analysis/icu/ICUAnalyzer.h
src/test/CMakeLists.txt
src/test/analysis/TestICU.cpp

1. Compilation error in Doris
2. Directory configuration error in Doris
3. ICU analyzer is missing the reader configuration.

[fix](analyzer) Fix ICU tokenizer error

---

src/core/CLucene/store/IndexInput.cpp
src/core/CLucene/store/IndexOutput.cpp
src/test/CMakeLists.txt
src/test/store/TestUTF8Chars.cpp
src/test/test.h
src/test/tests.cpp

[fix](unicode) fix 4 bytes unicode read and write bug

---

c++/src/Reader.cc

[fix] Load StripeIndex if searchArgument not exist.

[fix] Load StripeIndex if searchArgument not exist.

---

c++/src/Reader.cc

[opt] Load StripeIndex if searchArgument not exist when filter is not null.

[opt] Load StripeIndex if searchArgument not exist when filter is not null.

---

src/core/CLucene/index/IndexReader.h
src/core/CLucene/index/MultiReader.cpp
src/core/CLucene/index/MultiReader.h
src/core/CLucene/index/MultiSegmentReader.cpp
src/core/CLucene/index/SegmentReader.cpp
src/core/CLucene/index/TermInfosReader.cpp
src/core/CLucene/index/Terms.h
src/core/CLucene/index/_MultiSegmentReader.h
src/core/CLucene/index/_SegmentHeader.h
src/core/CLucene/index/_TermInfosReader.h
src/core/CLucene/util/bkd/bkd_reader.cpp
src/core/CLucene/util/bkd/bkd_reader.h
src/test/CMakeLists.txt
src/test/index/TestIndexReader2.cpp
src/test/test.h
src/test/tests.cpp

pick https://github.com/apache/doris-thirdparty/pull/295

[opt](inverted index) Enhance I/O statistics collection for the inverted index in file cache scenarios (#295)

---

c++/src/Reader.cc
c++/src/StripeStream.cc
c++/src/StripeStream.hh

[Optimize] Optimize stripe footer multiple reads.

[Optimize] Optimize stripe footer multiple reads.

---

c++/src/Compression.cc

[opt] Decompress zlib by libdeflate.

---

src/core/CLucene/index/DirectoryIndexReader.cpp
src/core/CLucene/index/IndexWriter.cpp
src/core/CLucene/index/IndexWriter.h
src/core/CLucene/index/SDocumentWriter.h

branch-3.0: [fix](index reader) fix memory leak 

---

c++/include/orc/Reader.hh
c++/src/Reader.cc
c++/src/sargs/SargsApplier.cc

[Enhancement] Add ReadRowCount metric.

---

.github/workflows/build-1.2.yml
.github/workflows/build-2.0.yml
.github/workflows/build-3.0.yml
.github/workflows/build.yml

https://github.com/actions/runner-images/issues/12520

change macos-latest to macos-14
